FROM ubuntu:latest

CMD ["bash"]

# RUN apt-get update \
#    apt-get install bash jq curl avahi-daemon dbus software-properties-common apparmor-utils \
#    curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s -- -d /home/user/docker/hassio
