version: '2'

services:
  kea:
    container_name: hassio
    build:
      context: ./Hassio
      dockerfile: Dockerfile
    privileged: true
    restart: unless-stopped
    network_mode: host
    ports:
      - "8123:8123"
