version: '2.1'

volumes:
  volume_adguard_conf:
  volume_adguard_work:
  volume_homeassistant:
  volume_hass_config:
  volume_node_red:
  volume_mosquitto:
  volume_dhcp:
  volume_node:

services:

  adguard:
    container_name: adguard
    image: "adguard/adguardhome:arm64-latest"
    volumes:
      - 'volume_adguard_work:/opt/adguardhome/work'
      - 'volume_adguard_conf:/opt/adguardhome/conf'
    network_mode: host

  mqtt:
    container_name: mosquitto
    image: arm64v8/eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - volume_mosquitto:/mosquitto

  homeassistant:
    build: Homeassistant
    restart: unless-stopped
    depends_on:
      - mqtt
    volumes:
      - volume_homeassistant:/config
    ports:
      - 8123:8123
    network_mode: host

  hass-configurator:
    image: "causticlab/hass-configurator-docker:arm"
    restart: always
    ports:
      - 3218:3218
    volumes:
      - volume_homeassistant:/hass-config
      - volume_mosquitto:/mosquitto
    environment:
      - HC_BASEPATH=/hass-config

  nodered:
    container_name: nodered
    image: nodered/node-red
    depends_on:
      - mqtt
      - homeassistant
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
      - volume_node_red:/data
    environment:
      TZ: "Europe/Luxembourg"

  isc-dhcp:
    image: "networkboot/dhcpd"
    network_mode: host
    volumes:
    - volume_dhcp:/data/

  glass:
    image: "node:8"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - volume_node:/home/node/app
      - volume_dhcp:/var/lib/dhcp
      - volume_dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
    ports:
      - "8080:8080"
      - "3000:3000"
    command: "/bin/sh -c 'npm install && npm start'"
