bonne version: '2.1'

volumes:
  volume_adguard_conf:
  volume_adguard_work:
  volume_homeassistant:
  volume_hass_config:
  volume_node_red:
  volume_mosquitto:
  volume_dhcp:
  volume_node:
  volume_appdaemon:
  volume_mariadb:

services:

  adguard:
    container_name: adguard
    image: "adguard/adguardhome:arm64-latest"
    volumes:
      - 'volume_adguard_work:/opt/adguardhome/work'
      - 'volume_adguard_conf:/opt/adguardhome/conf'
    network_mode: host

  homeassistant:
    build: Homeassistant
    restart: always
    depends_on:
      - mqtt
      # - mariadb
    volumes:
      - volume_homeassistant:/config
    ports:
      - 8123:8123
    network_mode: host

  mqtt:
    container_name: mosquitto
    image: arm64v8/eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - volume_mosquitto:/mosquitto

  # mariadb:
  #   image: jsurf/rpi-mariadb
  #   restart: unless-stopped
  #   # environment:
  #   #   MYSQL_ROOT_PASSWORD: "Emtk57"
  #   #   MYSQL_DATABASE: ha_db
  #   #   MYSQL_USER: homeassistant
  #   #   MYSQL_PASSWORD: "emtk57"
  #   volumes:
  #     - volume_mariadb:/var/lib/mysql
  #   ports:
  #     - 3306:3306

  # appdaemon:
  #   image : bubuplanet/appdaemon:latest
  #   restart: unless-stopped
  #   # environment:
  #   #   # HA_URL: "http://${SERVER_IP}:8123"
  #   #   # TOKEN: "${HA_APPDAEMON_KEY}"
  #   #   # DASH_URL: "http://${SERVER_IP}:5050"
  #   ports:
  #     - 5050:5050
  #   volumes:
  #     - volume_appdaemon:/conf
  #   depends_on:
  #     - homeassistant

  hass-configurator:
    image: "causticlab/hass-configurator-docker:arm"
    restart: always
    ports:
      - 3218:3218
    volumes:
      - volume_homeassistant:/hass-config
      - volume_mosquitto:/mosquitto
    environment:
      - HC_BASEPATH=/hass-config
      - HC_GIT=true

  nodered:
    container_name: nodered
    image: nodered/node-red
    depends_on:
      - mqtt
      - homeassistant
    restart: always
    ports:
      - 1880:1880
    volumes:
      - volume_node_red:/data
    environment:
      TZ: "Europe/Luxembourg"
