version: '2.1'

volumes:
  volume_adguard_conf:
  volume_adguard_work:
  volume_homeassistant:

services:

  adguard:
    container_name: adguard
    image: "adguard/adguardhome:arm64-latest"
    volumes:
      - 'volume_adguard_work:/opt/adguardhome/work'
      - 'volume_adguard_conf:/opt/adguardhome/conf'
    network_mode: host

  homeassistant:
    build:
      context: ./Homeassistant
      dockerfile: Dockerfile
    volumes:
      - volume_homeassistant:/config
    ports:
      - 8123:8123
    network_mode: host
