version: '2.1'

#                            #
#  LIVE DOCEKR COMPOSE FILES #
#                            #

volumes:
  volume_adguard_conf:
  volume_adguard_work:
  volume_homeassistant:
  volume_hass_config:
  volume_node_red:
  volume_mosquitto:
  volume_dhcp:
  volume_node:
  volume_appdaemon:
  volume_mariadb:

services:

  adguard:
    image: adguard/adguardhome:arm64-latest
    restart: unless-stopped
    volumes:
      - volume_adguard_work:/opt/adguardhome/work
      - volume_adguard_conf:/opt/adguardhome/conf
    network_mode: host

  homeassistant:
    image: homeassistant/home-assistant:0.113.2
    restart: always
    depends_on:
      - mqtt
      - mariadb
    volumes:
      - volume_homeassistant:/config
    ports:
      - 8123:8123
    network_mode: host

  mqtt:
    image: arm64v8/eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - volume_mosquitto:/mosquitto

  mariadb:
    image: jsurf/rpi-mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - volume_mariadb:/var/lib/mysql

  appdaemon:
    image: bubuplanet/appdaemon:latest
    restart: unless-stopped
    depends_on:
      - homeassistant
    ports:
      - 5050:5050
    volumes:
      - volume_appdaemon:/conf

  hass-configurator:
    image: causticlab/hass-configurator-docker:arm
    restart: unless-stopped
    ports:
      - 3218:3218
    volumes:
      - volume_homeassistant:/hass-config
      - volume_mosquitto:/mosquitto
    environment:
      - HC_BASEPATH=/hass-config
      - HC_GIT=true

  nodered:
    image: nodered/node-red
    restart: unless-stopped
    depends_on:
      - mqtt
      - homeassistant
    ports:
      - 1880:1880
    volumes:
      - volume_node_red:/data
    environment:
      TZ: "Europe/Luxembourg"
