version: '2.1'

volumes:
  volume_adguard_conf:
  volume_adguard_work:
  openhab_addons:
  openhab_conf:
  openhab_userdata:

services:
  adguard:
    container_name:
    image: "adguard/adguardhome:arm64-latest"
    volumes:
      - 'volume_adguard_work:/opt/adguardhome/work'
      - 'volume_adguard_conf:/opt/adguardhome/conf'
    network_mode: host

  openhab:
    container_name: openHab
    image: "openhab/openhab:2.5.3-snapshot-arm64-debian"
    # build:
    #   context: ./openHab
    #   dockerfile: Dockerfile
    restart: always
    network_mode: host
    privileged: true
    volumes:
      # - '/etc/localtime:/etc/localtime:ro'
      # - '/etc/timezone:/etc/timezone:ro'
      - 'openhab_addons:/openhab/addons'
      - 'openhab_conf:/openhab/conf'
      - 'openhab_userdata:/openhab/userdata'
    environment:
      OPENHAB_HTTP_PORT: '8080'
      OPENHAB_HTTPS_PORT: '8443'
      EXTRA_JAVA_OPTS: '-Duser.timezone=Europe/Berlin'
