version: '2.1'

volumes:
  volume_adguard_conf:
  volume_adguard_work:
  volume_homeassistant:
  volume_node_red:
  volume_mqtt_config:
  volume_mqtt_data:
  volume_mqtt_log:

services:

  adguard:
    container_name: adguard
    image: "adguard/adguardhome:arm64-latest"
    volumes:
      - 'volume_adguard_work:/opt/adguardhome/work'
      - 'volume_adguard_conf:/opt/adguardhome/conf'
    network_mode: host

  homeassistant:
    build:
      context: ./Homeassistant
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mqtt
    links:
      - mqtt
    volumes:
      - volume_homeassistant:/config
    ports:
      - 8123:8123
    network_mode: host
    environment:
      HA_SERVER_MQTT_HOST: 'mqtt'
      HA_SERVER_MQTT_PORT: '1883'

  nodered:
    container_name: nodered
    image: nodered/node-red
    restart: always
    ports:
      - 1880:1880
    volumes:
      - volume_node_red:/data
    depends_on:
      - homeassistant
    environment:
      TZ: "Europe/Luxembourg"

  mqtt:
    container_name: mosquitto
    build:
      context: ./Mosquitto
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - volume_mqtt_config:/mosquitto/config/mosquitto.conf
      - volume_mqtt_data:/mosquitto/data
      - volume_mqtt_log:/mosquitto/log
