version: '2'

services:
  # hassio:
  #   container_name: hassio
  #   build:
  #     context: ./Hassio
  #     dockerfile: Dockerfile
  #   privileged: true
  #   restart: unless-stopped
  #   network_mode: host
  #   ports:
  #     - "8123:8123"
  openhab:
    container_name: openHab
    image: "openhab/openhab:2.5.3-snapshot-armhf-debian"
    # build:
    #   context: ./openHab
    #   dockerfile: Dockerfile
    restart: always
    network_mode: host
    privileged: true
    # volumes:
    #   # - "/etc/localtime:/etc/localtime:ro"
    #   # - "/etc/timezone:/etc/timezone:ro"
    #   - "./openhab_addons:/openhab/addons"
    #   - "./openhab_conf:/openhab/conf"
    #   - "./openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
