     ##########################################################
     #                                                        #
     #.       LL       IIIIIIII  VV        VV  EEEEEEE        #
     #.       LL          II.     VV      VV.  EE             #
     #.       LL          II.      VV.   VV    EEEEEEE.       #
     #        LL          II.       VV. VV.    EE             #
     #        LLLLLLL. IIIIIIII       VV.      EEEEEEE        #
     #                                                        #
     ##########################################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  login_attempts_threshold: 5

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml

logger:
  default: warning
  #logs:
    #homeassistant.components.mqtt: debug

# Home Assistant side panel customization
panel_iframe:
  hassconf:
    title: HASS Configuration
    icon: mdi:lightbulb-on
    url: !secret HassConf

  nodered:
    title: Node-Red
    icon: mdi:access-point
    url: !secret NodeRed

# Text to speech
tts:
  - platform: google_translate

notify:

##########################
#                        #
#     HomeKit            #
#                        #
##########################
homekit:
  filter:
    include_domains:
      - media_player
    include_entities:
      - cover.shelly_shsw_25_1128a6
      - cover.shelly_shsw_25_f3fe95
      - cover.shelly_shsw_25_BCDDC277A2A9
      - cover.shelly_shsw_25_BCDDC277652D
      - cover.shelly_shsw_25_BCDDC2776E8D
      - cover.shelly_shsw_25_E098068D4103
  entity_config:
    media_player.living_room_tv:
      feature_list:
        - feature: on_off
        - feature: toggle_mute

##########################
#                        #
#     Media Player       #
#                        #
##########################
wake_on_lan: # enables `wake_on_lan` domain

media_player:

webostv:
  name: Living Room TV
  host: 192.168.187.69
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret LGwebOSTV_MAC
  customize:
    sources:
      - Amazon Prime Video
      - DJTV
      - HDMI 1
      - HDMI 2
      - HDMI 3
      - HDMI 4
      - Netflix
      - Smart IPTV
      - YouTube

##########################
#                        #
#     Shelly Config      #
#                        #
##########################

shelly:
  username: admin
  password: !secret shelly_password
  discovery: false
  sensors:
    - all
  devices:
    - id: "1128A6"
      name: Blind Dinning
    - id: "F3FE95"
      name: Blind Kitchen
    - id: "BCDDC277A2A9"
      name: Blind Living Side
    - id: "BCDDC277652D"
      name: Blind Living Side Small
    - id: "BCDDC2776E8D"
      name: Blind Living
    - id: "E098068D4103"
      name: Blind Living Stairs
#   - id: "6F5670"
#      name: Living Light
#      light_switch: true

light:
 - platform: mqtt
   schema: template
   name: Light Living
   state_topic: "shellies/ShellyVintage-6F5670/light/0/status"
   state_template: '{% if value_json.ison %} on {% else %} off {% endif %}'
   command_topic: "shellies/ShellyVintage-6F5670/light/0/set"
   command_on_template: '{"turn": "on"{% if brightness is defined %}, "brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}{% endif %}}'
   command_off_template: '{"turn": "off"}'
   brightness_template: '{{ (value_json.brightness | float * 2.55) | round(0) }}'
   retain: true

mqtt:
  broker: 192.168.187.28
  password: !secret mqtt

